import tkinter as tk
from tkinter import ttk


# Create the main window
def addnewmember():
    def on_canvas_scroll(event):
        canvas.yview_scroll(-1 * (event.delta // 120), "units")

    def go_back():
        root.destroy()
    root = tk.Tk()
    root.title("Add New Member")
    screen_width = root.winfo_screenwidth()
    screen_height = root.winfo_screenheight()
    root.geometry(f"{screen_width}x{screen_height}")
    # Set the background color to gray
    # Set the borderwidth and relief to create a border around the main window
    # Set the background color, borderwidth, relief, and internal padding for the root window
    root.configure(bg="lightgray", borderwidth=8, relief="ridge")

    # Create a canvas for scrollable content
    canvas = tk.Canvas(root, bg="lightgray")
    canvas.pack(side="left", fill="both", expand=True)

    # Add a vertical scrollbar
    scrollbar = tk.Scrollbar(root, command=canvas.yview)
    scrollbar.pack(side="right", fill="y")

    # Configure the canvas to use the scrollbar
    canvas.configure(yscrollcommand=scrollbar.set)

    # Create a frame inside the canvas to hold the content
    frame = tk.Frame(canvas, bg="lightgray")
    canvas.create_window((0, 0), window=frame, anchor="nw")

    # Bind the canvas to handle resizing and scrolling with the mouse wheel
    frame.bind("<Configure>", lambda e: canvas.configure(scrollregion=canvas.bbox("all")))
    canvas.bind("<MouseWheel>", on_canvas_scroll)
    framet = tk.Frame(frame, bg="lightgray")
    framet.pack(side="top", fill="x", expand=True)
    # Add "Back" button on the right side
    back_button = tk.Button(framet, text="Back", width=12, font=("Judons bold", 16), bg="white", fg="black", bd=1,
                            relief="solid", command=go_back)
    back_button.pack(side="right")

    custom_style = ttk.Style()
    custom_style.configure("framt.TFrame", background="lightgray")
    label = tk.Label(framet, text="Pazhaya Kotta Hanafi Jumma Masjith,", bg="lightgray", font="Inter 16")
    label.pack(side="top", padx=(50, 0), pady=(10, 0), fill="x", expand=True)
    label = tk.Label(framet, text="Parakunnam, Palakkad.", bg="lightgray", font="Inter 16")
    label.pack(side="top", padx=(50, 0), pady=(0, 10), fill="x", expand=True)
    label = tk.Label(framet, text="Bio-Data", font="Inter 16 bold", bg="lightgray")
    label.pack(side="top", pady=10, padx=(50, 0), fill="x", expand=True)
    subframe = tk.Frame(frame, bg="lightgray")
    subframe.pack(side="top", fill="x", padx=10)
    sub1 = tk.Frame(subframe, bg="lightgray")
    sub1.pack(side="left")

    label = tk.Label(sub1, text="Name :", bg="lightgray", font="Inter 16")
    label.grid(row=0, column=0)
    label = tk.Label(sub1, text="Father's Name :", bg="lightgray", font="Inter 16")
    label.grid(row=1, column=0)
    label = tk.Label(sub1, text="Aadhar :", bg="lightgray", font="Inter 16")
    label.grid(row=2, column=0)
    label = tk.Label(sub1, text="Address :", bg="lightgray", font="Inter 16")
    label.grid(row=3, column=0)
    label = tk.Label(sub1, text="Date Of Birth :", bg="lightgray", font="Inter 16")
    label.grid(row=4, column=0)
    label = tk.Label(sub1, text="Phone Number :", bg="lightgray", font="Inter 16")
    label.grid(row=5, column=0)
    label = tk.Label(sub1, text="Qualification :", bg="lightgray", font="Inter 16")
    label.grid(row=6, column=0)
    label = tk.Label(sub1, text="JOB :", bg="lightgray", font="Inter 16")
    label.grid(row=7, column=0)
    sub1.rowconfigure((0, 1, 2, 3, 4, 5, 6, 7), weight=1)
    entry1 = tk.Text(sub1, font="Inter 16", width=30, height=1)
    entry1.grid(row=0, column=1, padx=10, pady=10)
    entry2 = tk.Text(sub1, font="Inter 16", width=30, height=1)
    entry2.grid(row=1, column=1, padx=10, pady=10)
    entry3 = tk.Text(sub1, font="Inter 16", width=30, height=1)
    entry3.grid(row=2, column=1, padx=10, pady=10)
    entry4 = tk.Text(sub1, font="Inter 16", width=30, height=1)
    entry4.grid(row=3, column=1, padx=10, pady=10)
    entry5 = tk.Text(sub1, font="Inter 16", width=30, height=1)
    entry5.grid(row=4, column=1, padx=10, pady=10)
    entry6 = tk.Text(sub1, font="Inter 16", width=30, height=1)
    entry6.grid(row=5, column=1, padx=10, pady=10)
    entry7 = tk.Text(sub1, font="Inter 16", width=30, height=1)
    entry7.grid(row=6, column=1, padx=10, pady=10)
    entry8 = tk.Text(sub1, font="Inter 16", width=30, height=1)
    entry8.grid(row=7, column=1, padx=10, pady=10)
    sub2 = tk.Frame(subframe, bg="lightgray")
    sub2.pack(side="left")
    sub21 = tk.Frame(sub2, bg="lightgray")
    sub21.pack(side="top")
    label = tk.Label(sub21, text="Member No :", bg="lightgray", font="Inter 16")
    # label.grid(row=0,column=0,padx=10,pady=10)
    label.pack(side="left", padx=(350, 10), pady=(0, 10))
    entry9 = tk.Text(sub21, font="Inter 20", width=10, height=1)
    entry9.pack(side="left", pady=(0, 10))
    # entry9.grid(row=0,column=1,pady=10)
    entry10 = tk.Text(sub2, font="Inter 20", width=15, height=7)
    # entry10.grid(row=0,column=0,padx=10,pady=10)
    entry10.pack(side="bottom", pady=50, padx=(200, 0))
    sub3 = tk.Frame(frame, bg="lightgray")
    sub3.pack(side="top", fill="x", pady=20)
    sub32 = tk.Frame(sub3, bg="lightgray")
    sub32.pack(side="left", fill="x")
    label = tk.Label(sub32, text="Monthly Income :", font=" inter 16", bg="lightgray")
    # label.pack(side="left",padx=10)
    label.grid(row=0, column=0)

    label = tk.Label(sub32, text="Professional Income ", font=" inter 16", bg="lightgray")
    label.grid(row=0, column=1)
    label = tk.Label(sub32, text="Other Income ", font=" inter 16", bg="lightgray")
    label.grid(row=0, column=2)
    entry11 = tk.Text(sub32, font="Inter 16", width=20, height=1)
    entry11.grid(row=1, column=1, padx=10, pady=10)
    entry12 = tk.Text(sub32, font="Inter 16", width=20, height=1)
    entry12.grid(row=1, column=2, padx=10, pady=10)
    sub32.columnconfigure((1, 2), weight=10)
    sub4 = tk.Frame(frame, bg="lightgray")
    sub4.pack(side="top", fill="x", pady=20)
    sub42 = tk.Frame(sub4, bg="lightgray")
    sub42.pack(side="left", fill="x")
    label = tk.Label(sub42, text="Family   details  :", font=" inter 16", bg="lightgray")
    # label.pack(side="left",padx=10)
    label.grid(row=0, column=0)

    label = tk.Label(sub42, text="Wife Name", font=" inter 16", bg="lightgray")
    label.grid(row=0, column=1, pady=5)
    label = tk.Label(sub42, text="Children", font=" inter 16", bg="lightgray")
    label.grid(row=0, column=2, pady=5)
    entry13 = tk.Text(sub42, font="Inter 16", width=20, height=1)
    entry13.grid(row=1, column=1, padx=10, pady=10)
    entry14 = tk.Text(sub42, font="Inter 16", width=20, height=1)
    entry14.grid(row=1, column=2, padx=10, pady=10)
    label = tk.Label(sub42, text="Male", font=" inter 16", bg="lightgray")
    label.grid(row=2, column=1, pady=5)
    label = tk.Label(sub42, text="Female", font=" inter 16", bg="lightgray")
    label.grid(row=2, column=2, pady=5)
    entry15 = tk.Text(sub42, font="Inter 16", width=20, height=1)
    entry15.grid(row=3, column=1, padx=10, pady=10)
    entry16 = tk.Text(sub42, font="Inter 16", width=20, height=1)
    entry16.grid(row=3, column=2, padx=10, pady=10)
    sub42.columnconfigure((1, 2), weight=10)
    label = tk.Label(sub42, text="Students", font=" inter 16", bg="lightgray")
    label.grid(row=4, column=1, pady=5)
    label = tk.Label(sub42, text="Married", font=" inter 16", bg="lightgray")
    label.grid(row=4, column=2, pady=5)
    label = tk.Label(sub42, text="Widow / Divorced", font=" inter 16", bg="lightgray")
    label.grid(row=4, column=3, pady=5)
    entry17 = tk.Text(sub42, font="Inter 16", width=20, height=1)
    entry17.grid(row=5, column=1, padx=10, pady=10)
    entry18 = tk.Text(sub42, font="Inter 16", width=20, height=1)
    entry18.grid(row=5, column=2, padx=10, pady=10)
    entry19 = tk.Text(sub42, font="Inter 16", width=20, height=1)
    entry19.grid(row=5, column=3, padx=10, pady=10)
    sub42.columnconfigure((1, 2, 3), weight=10)
    sub5 = tk.Frame(frame, bg="lightgray")
    sub5.pack(side="top", fill="x", pady=20)
    sub52 = tk.Frame(sub5, bg="lightgray")
    sub52.pack(side="left", fill="x")
    label = tk.Label(sub52, text="Health Conditions :", font=" inter 16", bg="lightgray")
    label.grid(row=0, column=0)
    label = tk.Label(sub52, text="Pressure", font=" inter 16", bg="lightgray")
    label.grid(row=1, column=1, pady=5)
    label = tk.Label(sub52, text="Sugar", font=" inter 16", bg="lightgray")
    label.grid(row=1, column=2, pady=5)
    label = tk.Label(sub52, text="Heart", font=" inter 16", bg="lightgray")
    label.grid(row=1, column=3, pady=5)
    label = tk.Label(sub52, text="Cancer", font=" inter 16", bg="lightgray")
    label.grid(row=1, column=4, pady=5)
    label = tk.Label(sub52, text="Kidney", font=" inter 16", bg="lightgray")
    label.grid(row=1, column=5, pady=5)
    entry20 = tk.Text(sub52, font="Inter 16", width=10, height=1)
    entry20.grid(row=2, column=1, padx=10, pady=10)
    entry21 = tk.Text(sub52, font="Inter 16", width=10, height=1)
    entry21.grid(row=2, column=2, padx=10, pady=10)
    entry22 = tk.Text(sub52, font="Inter 16", width=10, height=1)
    entry22.grid(row=2, column=3, padx=10, pady=10)
    entry23 = tk.Text(sub52, font="Inter 16", width=10, height=1)
    entry23.grid(row=2, column=4, padx=10, pady=10)
    entry24 = tk.Text(sub52, font="Inter 16", width=10, height=1)
    entry24.grid(row=2, column=5, padx=10, pady=10)
    sub52.columnconfigure((1, 2, 3, 4, 5), weight=10)
    sub6 = tk.Frame(frame, bg="lightgray")
    sub6.pack(side="top", fill="x", pady=20)
    sub61 = tk.Frame(sub6, bg="lightgray")
    sub61.pack(side="left", fill="x")
    label = tk.Label(sub61, text="Place :", font=" inter 16", bg="lightgray")
    label.grid(row=0, column=0, padx=(10, 90))
    label = tk.Label(sub61, text="Date :", font=" inter 16", bg="lightgray")
    label.grid(row=1, column=0, padx=(10, 90))
    entry25 = tk.Text(sub61, font="Inter 16", width=20, height=1)
    entry25.grid(row=0, column=1, padx=10, pady=10)
    entry26 = tk.Text(sub61, font="Inter 16", width=20, height=1)
    entry26.grid(row=1, column=1, padx=10, pady=10)
    sub62 = tk.Frame(sub6, bg="lightgray")
    sub62.pack(side="left", fill="x")
    label = tk.Label(sub62, text="Signature :", font=" inter 16", bg="lightgray")
    label.grid(row=0, column=0, padx=(90, 90))
    label = tk.Label(sub62, text="Name :", font=" inter 16", bg="lightgray")
    label.grid(row=1, column=0, padx=(90, 90))
    entry27 = tk.Text(sub62, font="Inter 16", width=20, height=1)
    entry27.grid(row=0, column=1, padx=10, pady=10)
    entry28 = tk.Text(sub62, font="Inter 16", width=20, height=1)
    entry28.grid(row=1, column=1, padx=10, pady=10)
    sub7 = tk.Frame(frame, bg="lightgray")
    sub7.pack(side="top", fill="x")
    btnc = tk.Button(sub7, text="Confirm Details", font="Inter 16", bg="#88D1E8", height=2, width=20)
    btnc.pack(side="top", pady=50,padx=(0,40))
    root.mainloop()
